[package]
name = "onnxrt"
version = "0.1.0"
authors = ["FuriosaAI Inc."]
description = "OnnxRt provides mid-level Rust bindings to the C API for Microsoft's ONNX Runtime."
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/furiosa-ai/onnxrt"
keywords = ["onnx", "neuralnetworks", "ffi", "bindings"]
categories = ["science", "external-ffi-bindings"]
documentation = "https://furiosa-ai.github.io/onnxrt/0.1.0/onnxrt"
edition = "2018"

[dependencies]
once_cell = "1.7.2"
onnxruntime-sys = "0.0.10"
