[advisories]
ignore = [
  "RUSTSEC-2020-0071",
]

[licenses]
copyleft = "deny"
confidence-threshold = 1.0
allow = [
  "Apache-2.0",
  "ISC",
  "MIT",
  "MPL-2.0",
  "OpenSSL",
  "Zlib",
]

[[licenses.clarify]]
name = "webpki"
expression = "ISC"
license-files = [
    { path = "LICENSE", hash = 0x001c7e6c },
]

[[licenses.clarify]]
name = "ring"
expression = "ISC AND OpenSSL AND MIT"
license-files = [
    { path = "LICENSE", hash = 0xbd0eed23 },
]

[sources]
allow-git = [
  "https://github.com/furiosa-ai/onnxrt-sys.git"
]
